In [2]:
import numpy as np

In [7]:
array1 = np.arange(15, 41)
print(array1)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40]


In [9]:
array2=np.arange(10, 26)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [11]:
even_array1 = np.arange(2, 21, 2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
even_array2=np.arange(34, 53, 2)
even_array2

array([34, 36, 38, 40, 42, 44, 46, 48, 50, 52])

In [23]:
a= np.stack((even_array1, even_array2))
a

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [34, 36, 38, 40, 42, 44, 46, 48, 50, 52]])

In [25]:
array3 = np.arange(0, 36)
array3
array3=array3.reshape(6,6)
array3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [28]:
print(array3[3, 2])

20


In [34]:
abc = np.random.randn(5, 2)
abc


array([[-2.86217217, -1.1518384 ],
       [ 0.12081023, -0.81693861],
       [-1.06339832,  0.03705443],
       [-0.34306363, -0.23856446],
       [ 0.37379047, -0.87074066]])

In [35]:
nn = abc[-1, -1]
nn

np.float64(-0.8707406585188877)

In [41]:
aaa = abc.mean()
aaa

np.float64(-0.6815061108952623)

In [2]:
import numpy as np

data = [1,5,7,8, 9, 9, 3, 5, 6,]

np.mode(data)

AttributeError: module 'numpy' has no attribute 'mode'